language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c "CREATE DATABASE teamworkdb;" -U postgres
  - psql -c "CREATE USER kola WITH PASSWORD 'pedro123';" -U postgres

  - npm run build
script:
  - npm run int:test
after_success:
  - npm run coveralls
notifications:
  email: false

