language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database teamworkdb;' -U postgres
  - npm run build
script:
  - npm run int:test
#after_success:
 # - npm run coveralls


